#
# Install developer packages
#
- name: Install DNF packages and update cache
  become: yes
  tasks:
    - name: Install packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - alacritty
        - bash-color-prompt
        - bash-completion
        - exa
        - fd-find
        - fzf
        - gcc
        - git
        - make
        - neovim
        - ripgrep
        - strace
        - tmux
        - unzip
        - zoxide

    - name: Update package cache
      dnf:
        update_cache: yes

