#
# Install developer packages
#
- name: Install packages
  ansible.builtin.dnf:
    name:
      - alacritty
      - bash-color-prompt
      - bash-completion
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - exa
      - fd-find
      - fzf
      - gcc
      - git
      - make
      - neovim
      - ripgrep
      - stow
      - strace
      - tig
      - tmux
      - unzip
      - zoxide
    state: present
    update_cache: true

- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: "https://github.com/cpeters/dotfiles.git"
    dest: "/home/chris/.dotfiles"
    clone: true

# TODO fix structure of stow repo and update these
- name: Use stow to manage dotfiles
  ansible.builtin.command: stow -t ~/ {{ item }}
  args:
    chdir: "/home/chris/.dotfiles"
  with_items:
  # - bash
  # - alacritty
    - git
    - tmux
