---
#
# Setup environment for containers
#
- name: Add Copr repository for Incus
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: ganto/lxc4

- name: Install packages
  ansible.builtin.dnf5:
    name:
      - cockpit-podman
      - incus
      - podman
      - podman-compose
      - podman-docker
      - podman-plugins
      - podman-remote
    state: present
    update_cache: true

- name: Install Flatpak apps
  community.general.flatpak:
    name:
      - io.podman_desktop.PodmanDesktop
    method: user
    state: present

# vim: ts=2 sts=2 sw=2 et ft=yaml.ansible
