#
# Install Gnome packages and tweak default behavior
#
- name: Install DNF packages from list
  become: yes
  tasks:
    - name: Install packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - gnome-extensions-app
        - gnome-tweaks
        - flatseal

- name: Install individual GNOME extensions
  become: yes
  vars:
    extensions_dir: "~/.local/share/gnome-shell/extensions"
    extensions:
      - name: "Vitals@CoreCoding.com"
        repo: "https://github.com/corecoding/Vitals.git"
      - name: "dash-to-dock@micxgx.gmail.com"
        repo: "https://github.com/micheleg/dash-to-dock.git"
      - name: "blue-my-shell@aunetx"
        repo: "https://github.com/aunetx/blur-my-shell.git"
  tasks:
    - name: Ensure git is installed
      dnf:
        name: git
        state: present

    - name: Clone and install extensions
      git:
        repo: "{{ item.repo }}"
        dest: "{{ extensions_dir }}/{{ item.name }}"
        update: yes
        force: yes
      with_items: "{{ extensions }}"

#
# Default setting for Gnome groups all windows by app together when using Alt-Tab
# Modify this behavior to display all open windows on a active workspace when using Alt-Tab
# Default setting for Option-Tab will remain unmodified and allow switching by app group across all workspace
#
# Alt-Tab - individual windows on active workspace
# Option-Tab - grouped by application across all workspaces
#
- name: Edit GNOME default switching behavior
  become: yes
  tasks:
    - name: Set switch-windows keybinding
      command: gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab']"

    - name: Set switch-windows-backward keybinding
      command: gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "['<Alt><Shift>Tab']"

