#
# Setup environment for containers
#
- name: Add Copr repository for Incus
  command: dnf copr enable -y ganto/lxc4

- name: Install DNF packages and update cache
  become: yes
  tasks:
    - name: Install packages
      dnf:
        name:
          - cockpit-podman
          - incus
          - podman
          - podman-compose
          - podman-docker
          - podman-plugins
          - podman-remote
        state: present
        update_cache: yes

- name: Install Flatpak apps
  become: yes
  tasks:
    - name: Install Flatpak apps
      command: flatpak install -y flathub {{ item }}
      loop:
        - io.podman_desktop.PodmanDesktop

